title: WachsenLassen
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://www.wachsenlassenmr.ml/
baseurl: #
paginate_path: "blog/page:num/"
permalink: http://www.wachsenlassenmr.ml/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
port: 4001

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: brianmaierjr
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
