title: Wachsen Lassen E. V.
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: "" # http://www.wachsenlassenmr.ml/
baseurl: #
paginate_path: "blog/page:num/"
permalink: 

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
port: 4040

navigation:
  - title: Gartenprojekt
    url: /index.html
  - title: Neues
    url: /articles
  - title: Kontakt
    url: /contact
  - title: Fotogallerie
    url: /gallerie

social:
  github: https://github.com/lgiese/lgiese.wachsenlassenEV.io
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
