title: Wachsen Lassen E. V.
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/lgiese/lgiese.wachsenlassenEV.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: 

markdown: kramdown
highlighter: rouge
plugins:
  - fullcalendar-rails
  - momentjs-rails
paginate: 3
port: 4004

navigation:
  - title: WasHierLos?
    url: /index.html
  - title: So läuft´s
    url: /gartenprojekt
  - title: Neues
    url: /neues
  - title: Fotogallerie
    url: /gallerie
  - title: Kalender
    url: /calender
  - title: Kontakt
    url: /contact
    
gems:
  - jekyll-leaflet
  - jekyll-paginate

social:
  github: https://github.com/lgiese/lgiese.wachsenlassenEV.io
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
