title: Wachsen Lassen E. V.
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://github.com/lgiese/lgiese.wachsenlassenEV.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: 

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3
port: 4040

navigation:
  - title: WasHierLos?
    url: /index.html
  - title: Gartenprojekt
    url: /gartenprojekt
  - title: Neues
    url: /neues
  - title: Fotogallerie
    url: /gallerie
  - title: Kontakt
    url: /contact

social:
  github: https://github.com/lgiese/lgiese.wachsenlassenEV.io
  twitter: brianmaierjr
  facebook: brianmaierjr
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
